@startuml
 'https://plantuml.com/class-diagram

title Vista fisica nível 2

 hide circle
 skinparam classAttributeIconSize 0

node "Instance 1 "{
    component ReaderCom
}

node " Instance 1  "{
    component ReaderQuery
}

node " Instance 1   "{
    component BookCom
}

node " Instance 1    "{
    component BookQuery
}

node " Instance 1     "{
    component AuthCommand
}

node " Instance 1      "{
    component AuthQuery
}


node "Instance  1       "{
    component LendingCom
}

node " Instance 1        "{
    component LendingQuery
}




@enduml
